# Site settings
title: Verbosidade
description: Verbosidade é um Blog pessoal de Alex Farias sobre Tecnologia, Aprendizagem de Máquina, Inteligência Artificial, Notas de Estudo, Desenvolvimento de Software, Javascript, Java, HTML, CSS, nodejs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://astfarias.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alex Farias
user_description: Estudante de computação e Analista em AIDAX
email: astfarias@gmail.com
twitter_username: astfarias
github_username:  astfarias
gplus_username:  AlexFarias-astfarias
disqus_username: astfarias

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Categorias
    url: /series
  - title: "#Tags"
    url: /tags
  # - title: About Me
  #   url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
